language: generic
sudo: required
# ^ required for Docker
services:
  - docker

before_install:
  - docker build -t elohmrow/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true elohmrow/multi-docker npm run test

after_success:
  - docker build -t elohmrow/multi-docker-client ./client
  - docker build -t elohmrow/multi-docker-server ./server
  - docker build -t elohmrow/multi-docker-nginx ./nginx
  - docker build -t elohmrow/multi-docker-worker ./worker
  # push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push multi-docker-client
  - docker push multi-docker-nginx
  - docker push multi-docker-server
  - docker push multi-docker-worker